---
- name: Add Google Chrome Repository Key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome Repository
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes

- name: Determine Latest ChromeDriver Version
  set_fact:
    chromedriver_version: "{{ lookup('url', 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE') }}"

- name: Install ChromeDriver
  unarchive:
    src: http://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Configure UFW
  ufw:
    rule: allow
    port: 9515
  when: inventory_hostname in groups['development']
