---
server_rtc: 0
server_timezone: UTC
server_ntp: 1
server_locale: en_US.UTF-8
server_dns:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
server_user_add_authorized_key: true
server_disable_ssh_root_login: false
server_disable_ssh_password_login: true
server_fix_vm_networking: true