---
- name: Add Ruby PPA
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install Ruby
  apt:
    name:
      - ruby{{ ruby_version }}
      - ruby{{ ruby_version }}-dev
      - ruby-switch
    state: latest
    update_cache: yes

- name: Set Ruby Global Version
  shell: "ruby-switch --set ruby{{ ruby_version }}"

- name: Install Backup Dependencies
  apt:
    name:
      - libsqlite3-dev
      - libxslt-dev
      - libxml2-dev
      - zlib1g-dev
    state: latest
  ignore_errors: yes

- name: Install Mailcatcher
  shell: gem{{ ruby_version }} install mailcatcher --no-document

- name: Configure Mailcatcher Service
  copy:
    src: mailcatcher.service
    dest: /lib/systemd/system
    owner: root
    group: root
    mode: 0644
  notify: Start Mailcatcher

- name: Start Mailcatcher Upon Boot
  service:
    name: mailcatcher
    enabled: yes
