---
- name: Build Environment
  hosts: all
  become: yes
  roles:
    - role: swap
      tags: swap
      when: inventory_hostname in groups['development']

    - role: server

    - role: users
      tags: users

    - role: packages

    - role: php
      tags: php

    - role: nginx
      tags: nginx

    - role: caddy
      tags: caddy

    - role: certbot
      tags: certbot

    - role: mysql
      tags: mysql

    - role: redis
      tags: redis

    - role: mailcatcher
      tags: mailcatcher

    - role: nodejs
      tags: nodejs

    - role: go
      tags: go

    - role: chrome
      tags: chrome
